version: "3"

services:
  tstestproject:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/tsTestProject
    tty: true
    command: npm start
    ports:
      - 8080:8080
    container_name: tstestproject
